# generated by datamodel-codegen:
#   filename:  ec_curve_test_schema.json
#   timestamp: 2026-02-10T18:44:13+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, ConfigDict, Field, RootModel, constr


class Algorithm(Enum):
    EcCurveTest = 'EcCurveTest'


class Schema(Enum):
    ec_curve_test_schema_json = 'ec_curve_test_schema.json'


class Source(BaseModel):
    name: constr(min_length=1)
    version: constr(min_length=1)


class NoteEntry(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    description: str | None = Field(None, description='A description of the flag')
    bugType: str = Field(..., description='The type of the bug tested for')
    effect: str | None = Field(
        None, description='The expected effect of failing the test vector'
    )
    links: list[str] | None = Field(
        None, description='A list of potentially related references'
    )
    cves: list[str] | None = Field(
        None, description='A list of potentially related CVEs'
    )


class Type(Enum):
    EcCurveTest = 'EcCurveTest'


class Result(Enum):
    valid = 'valid'
    invalid = 'invalid'
    acceptable = 'acceptable'


class Test(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    tcId: int = Field(..., description='Identifier of the test case')
    comment: str | None = Field(
        None, description='A brief description of the test case'
    )
    flags: list[str] | None = Field(None, description='A list of flags')
    name: str | None = Field(None, description='Name identifying the elliptic curve')
    oid: str = Field(..., description='Object identifier of the ellptic curve')
    ref: str | None = Field(
        None, description='Standard containing the domain parameters'
    )
    p: str = Field(..., description='Prime identifying the field of definition')
    n: str = Field(..., description='Order of the curve')
    a: str = Field(..., description="Coefficient a of the curve's Weierstrass equation")
    b: str = Field(..., description="Coefficient b of the curve's Weierstrass equation")
    gx: str = Field(..., description="x coordinate of the curve's generator")
    gy: str = Field(..., description="y coordinate of the curve's generator")
    h: int = Field(..., description='Cofactor of the curve')
    result: Result = Field(..., description='Test result')


class EcCurveTest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Type
    source: Source
    tests: list[Test]


class Notes(RootModel[dict[str, NoteEntry]]):
    root: dict[str, NoteEntry]


class Model(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    algorithm: Algorithm
    schema_: Schema = Field(..., alias='schema')
    generatorVersion: str | None = Field(
        None,
        deprecated=True,
        description='DEPRECATED: prefer "source" property in test group',
    )
    numberOfTests: int = Field(
        ..., description='the number of test vectors in this test'
    )
    header: list[str] | None = Field(None, description='additional documentation')
    notes: Notes | None = None
    testGroups: list[EcCurveTest]
