# generated by datamodel-codegen:
#   filename:  ecdsa_verify_schema_v1.json
#   timestamp: 2026-02-10T18:44:18+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, ConfigDict, Field, RootModel, constr


class Schema(Enum):
    ecdsa_verify_schema_v1_json = 'ecdsa_verify_schema_v1.json'


class Source(BaseModel):
    name: constr(min_length=1)
    version: constr(min_length=1)


class NoteEntry(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    description: str | None = Field(None, description='A description of the flag')
    bugType: str = Field(..., description='The type of the bug tested for')
    effect: str | None = Field(
        None, description='The expected effect of failing the test vector'
    )
    links: list[str] | None = Field(
        None, description='A list of potentially related references'
    )
    cves: list[str] | None = Field(
        None, description='A list of potentially related CVEs'
    )


class Type(Enum):
    EcdsaVerify = 'EcdsaVerify'


class Type1(Enum):
    EcPublicKey = 'EcPublicKey'


class Type2(Enum):
    PrimeOrderCurve = 'PrimeOrderCurve'


class EcUnnamedGroup(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    a: str | None = Field(
        None, description='coefficient a of the elliptic curve equation'
    )
    b: str | None = Field(
        None, description='coefficient b of the elliptic curve equation'
    )
    gx: str | None = Field(None, description='the x-coordinate of the generator')
    gy: str | None = Field(None, description='the y-coordinate of the generator')
    h: int | None = Field(None, description='the cofactor')
    n: str | None = Field(None, description='the order of the generator')
    p: str | None = Field(None, description='the order of the underlying field')
    type: Type2 | None = Field(
        None, description='an unnamed EC group over a prime field in Weierstrass form'
    )


class Result(Enum):
    valid = 'valid'
    invalid = 'invalid'
    acceptable = 'acceptable'


class AsnSignatureTestVector(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    tcId: int | None = Field(None, description='Identifier of the test case')
    comment: str | None = Field(
        None, description='A brief description of the test case'
    )
    msg: str | None = Field(None, description='The message to sign')
    sig: str | None = Field(None, description='An ASN encoded signature for msg')
    result: Result | None = Field(None, description='Test result')
    flags: list[str] | None = Field(None, description='A list of flags')


class Notes(RootModel[dict[str, NoteEntry]]):
    root: dict[str, NoteEntry]


class EcPublicKey(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    curve: EcUnnamedGroup | str | None = Field(
        None, description='the EC group used by this public key'
    )
    keySize: int | None = Field(None, description='the key size in bits')
    type: Type1 | None = Field(None, description='the key type')
    uncompressed: str | None = Field(None, description='encoded public key point')
    wx: str | None = Field(None, description='the x-coordinate of the public key point')
    wy: str | None = Field(None, description='the y-coordinate of the public key point')


class EcdsaTestGroup(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Type | None = None
    source: Source
    publicKey: EcPublicKey | None = Field(None, description='unencoded EC public key')
    publicKeyDer: str | None = Field(None, description='DER encoded public key')
    publicKeyPem: str | None = Field(None, description='Pem encoded public key')
    sha: str | None = Field(None, description='the hash function used for ECDSA')
    tests: list[AsnSignatureTestVector] | None = None


class Model(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    algorithm: str | None = Field(
        None, description='the primitive tested in the test file'
    )
    generatorVersion: str | None = Field(
        None,
        deprecated=True,
        description='DEPRECATED: prefer "source" property in test group',
    )
    header: list[str] | None = Field(None, description='additional documentation')
    notes: Notes | None = None
    numberOfTests: int | None = Field(
        None, description='the number of test vectors in this test'
    )
    schema_: Schema | None = Field(None, alias='schema')
    testGroups: list[EcdsaTestGroup] | None = None
