# generated by datamodel-codegen:
#   filename:  hkdf_test_schema_v1.json
#   timestamp: 2026-02-10T18:44:20+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, ConfigDict, Field, RootModel, constr


class Schema(Enum):
    hkdf_test_schema_v1_json = 'hkdf_test_schema_v1.json'


class Source(BaseModel):
    name: constr(min_length=1)
    version: constr(min_length=1)


class NoteEntry(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    description: str | None = Field(None, description='A description of the flag')
    bugType: str = Field(..., description='The type of the bug tested for')
    effect: str | None = Field(
        None, description='The expected effect of failing the test vector'
    )
    links: list[str] | None = Field(
        None, description='A list of potentially related references'
    )
    cves: list[str] | None = Field(
        None, description='A list of potentially related CVEs'
    )


class Type(Enum):
    HkdfTest = 'HkdfTest'


class Result(Enum):
    valid = 'valid'
    invalid = 'invalid'
    acceptable = 'acceptable'


class HkdfTestVector(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    tcId: int | None = Field(None, description='Identifier of the test case')
    comment: str | None = Field(
        None, description='A brief description of the test case'
    )
    ikm: str | None = Field(None, description='the key (input key material)')
    salt: str | None = Field(None, description='the salt for the key derivation')
    info: str | None = Field(
        None, description='additional information used in the key derivation'
    )
    size: int | None = Field(None, description='the size of the output in bytes')
    okm: str | None = Field(
        None, description='the generated bytes (output key material)'
    )
    result: Result | None = Field(None, description='Test result')
    flags: list[str] | None = Field(None, description='A list of flags')


class Notes(RootModel[dict[str, NoteEntry]]):
    root: dict[str, NoteEntry]


class HkdfTestGroup(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Type | None = None
    source: Source
    keySize: int | None = Field(None, description='the size of the ikm in bits')
    tests: list[HkdfTestVector] | None = None


class Model(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    algorithm: str | None = Field(
        None, description='the primitive tested in the test file'
    )
    generatorVersion: str | None = Field(
        None,
        deprecated=True,
        description='DEPRECATED: prefer "source" property in test group',
    )
    header: list[str] | None = Field(None, description='additional documentation')
    notes: Notes | None = None
    numberOfTests: int | None = Field(
        None, description='the number of test vectors in this test'
    )
    schema_: Schema | None = Field(None, alias='schema')
    testGroups: list[HkdfTestGroup] | None = None
