# generated by datamodel-codegen:
#   filename:  json_web_encryption_schema_v1.json
#   timestamp: 2026-02-10T18:44:23+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, RootModel, constr


class Schema(Enum):
    json_web_encryption_schema_v1_json = 'json_web_encryption_schema_v1.json'


class Source(BaseModel):
    name: constr(min_length=1)
    version: constr(min_length=1)


class NoteEntry(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    description: str | None = Field(None, description='A description of the flag')
    bugType: str = Field(..., description='The type of the bug tested for')
    effect: str | None = Field(
        None, description='The expected effect of failing the test vector'
    )
    links: list[str] | None = Field(
        None, description='A list of potentially related references'
    )
    cves: list[str] | None = Field(
        None, description='A list of potentially related CVEs'
    )


class Type(Enum):
    JsonWebEncryption = 'JsonWebEncryption'


class Use(Enum):
    sig = 'sig'
    enc = 'enc'


class Kty(Enum):
    field_ = ''
    oct = 'oct'
    EC = 'EC'
    RSA = 'RSA'
    OKP = 'OKP'


class Crv(Enum):
    P_256 = 'P-256'
    P_256K = 'P-256K'
    P_384 = 'P-384'
    P_521 = 'P-521'
    secp256k1 = 'secp256k1'
    X448 = 'X448'
    X25519 = 'X25519'
    Ed25519 = 'Ed25519'
    Ed448 = 'Ed448'


class JsonWebKey(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    alg: str | None = Field(None, description='the encryption/signing algorithm to use')
    use: Use | None = Field(
        None, description='what type of crypto operation to perform'
    )
    key_ops: list[str] | None = Field(None, description='an alternative to use')
    kid: str | None = Field(None, description='the ID of the key entry')
    kty: Kty | None = Field(
        None, description='the family of algorithms the key belongs to'
    )
    k: str | None = Field(None, description='the secret key value of an oct key')
    n: str | None = Field(None, description='the public modulus of an RSA key')
    e: str | None = Field(None, description='the public exponent of an RSA key')
    p: str | None = Field(None, description='the first prime factgor of an RSA key')
    q: str | None = Field(None, description='the second prime factor of an RSA key')
    dp: str | None = Field(
        None,
        description='the first factor Chinese Remainder Theorem exponent of an RSA key',
    )
    dq: str | None = Field(
        None,
        description='the second factor Chinese Remainder Theorem exponent of an RSA key',
    )
    qi: str | None = Field(
        None,
        description='the first factor Chinese Remainder Theorem coefficient of an RSA key',
    )
    crv: Crv | None = Field(None, description='which defined curve to use')
    x: str | None = Field(None, description='the x-coordinate of an EC key point')
    y: str | None = Field(None, description='the y-coordinate of an EC key point')
    d: str | None = Field(
        None,
        description='the private key value of an EC key or private exponent for RSA',
    )


class JsonWebKeyset(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    keys: list[JsonWebKey] | None = None


class JsonWebKeyOrKeyset(RootModel[JsonWebKeyset | JsonWebKey]):
    root: JsonWebKeyset | JsonWebKey


class Recipient(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    header: dict[str, Any] | None = Field(
        None, description='header information that is not integrity protected'
    )
    encrypted_key: str | None = None


class Result(Enum):
    valid = 'valid'
    invalid = 'invalid'
    acceptable = 'acceptable'


class JsonWebEncryptionTestVector(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    tcId: int | None = Field(None, description='Identifier of the test case')
    comment: str | None = Field(
        None, description='A brief description of the test case'
    )
    jwe: str | None = Field(None, description='The JSON Web Encryption in compact form')
    pt: str | None = Field(None, description='[optional] Plaintext')
    enc: str | None = Field(None, description='the content encryption algorithm')
    result: Result | None = Field(None, description='Test result')
    flags: list[str] | None = Field(None, description='A list of flags')


class Notes(RootModel[dict[str, NoteEntry]]):
    root: dict[str, NoteEntry]


class JsonWebEncryptionTestGroup(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Type | None = None
    source: Source
    comment: str | None = Field(
        None, description='a description of what these tests have in common'
    )
    private: JsonWebKey | None = Field(None, description='the private key')
    public: JsonWebKey | None = Field(None, description='the [optional] public key')
    tests: list[JsonWebEncryptionTestVector] | None = None


class Model(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    generatorVersion: str | None = Field(
        None,
        deprecated=True,
        description='DEPRECATED: prefer "source" property in test group',
    )
    header: list[str] | None = Field(None, description='additional documentation')
    notes: Notes | None = None
    numberOfTests: int | None = Field(
        None, description='the number of test vectors in this test'
    )
    schema_: Schema | None = Field(None, alias='schema')
    testGroups: list[JsonWebEncryptionTestGroup] | None = None
