# generated by datamodel-codegen:
#   filename:  mlkem_encaps_test_schema.json
#   timestamp: 2026-02-10T18:44:32+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, ConfigDict, Field, RootModel, constr


class Algorithm(Enum):
    ML_KEM = 'ML-KEM'


class Schema(Enum):
    mlkem_encaps_test_schema_json = 'mlkem_encaps_test_schema.json'


class Source(BaseModel):
    name: constr(min_length=1)
    version: constr(min_length=1)


class NoteEntry(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    description: str | None = Field(None, description='A description of the flag')
    bugType: str = Field(..., description='The type of the bug tested for')
    effect: str | None = Field(
        None, description='The expected effect of failing the test vector'
    )
    links: list[str] | None = Field(
        None, description='A list of potentially related references'
    )
    cves: list[str] | None = Field(
        None, description='A list of potentially related CVEs'
    )


class Type(Enum):
    MLKEMEncapsTest = 'MLKEMEncapsTest'


class ParameterSet(Enum):
    ML_KEM_512 = 'ML-KEM-512'
    ML_KEM_768 = 'ML-KEM-768'
    ML_KEM_1024 = 'ML-KEM-1024'


class Result(Enum):
    valid = 'valid'
    invalid = 'invalid'
    acceptable = 'acceptable'


class Test(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    tcId: int = Field(..., description='Identifier of the test case')
    comment: str | None = Field(
        None, description='A brief description of the test case'
    )
    ek: str = Field(..., description='The encapsulation key')
    m: str = Field(..., description='The ML-KEM.Encaps_internal m input')
    c: str = Field(..., description='The output ciphertext')
    K: str = Field(..., description='The output shared secret')
    result: Result = Field(..., description='Test result')
    flags: list[str] = Field(..., description='A list of flags')


class MLKEMEncapsTestGroup(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Type | None = Field(
        None, description='A legacy field, test files contain only one type per file'
    )
    source: Source
    parameterSet: ParameterSet
    tests: list[Test]


class Notes(RootModel[dict[str, NoteEntry]]):
    root: dict[str, NoteEntry]


class Model(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    algorithm: Algorithm
    header: list[str] | None = Field(None, description='additional documentation')
    notes: Notes | None = None
    numberOfTests: int = Field(
        ..., description='the number of test vectors in this test'
    )
    schema_: Schema = Field(..., alias='schema')
    testGroups: list[MLKEMEncapsTestGroup]
