#!/usr/bin/env python3

"""
Generate `tests/src/test_certs.h` which includes certficaties/keys/certificate list for testing.
"""

#
# Copyright The Mbed TLS Contributors
# SPDX-License-Identifier: Apache-2.0 OR GPL-2.0-or-later


import argparse
import os
from typing import Iterator, List, Tuple

from mbedtls_framework.build_tree import guess_project_root

TESTS_DIR = os.path.join(guess_project_root(), 'tests')
FRAMEWORK_DIR = os.path.join(guess_project_root(), 'framework')
DATA_FILES_PATH = os.path.join(FRAMEWORK_DIR, 'data_files')

INPUT_ARGS = [
    ("string", "TEST_CA_CRT_EC_PEM", DATA_FILES_PATH + "/test-ca2.crt"),
    ("binary", "TEST_CA_CRT_EC_DER", DATA_FILES_PATH + "/test-ca2.crt.der"),
    ("string", "TEST_CA_KEY_EC_PEM", DATA_FILES_PATH + "/test-ca2.key.enc"),
    ("password", "TEST_CA_PWD_EC_PEM", "PolarSSLTest"),
    ("binary", "TEST_CA_KEY_EC_DER", DATA_FILES_PATH + "/test-ca2.key.der"),
    ("string", "TEST_CA_CRT_RSA_SHA256_PEM", DATA_FILES_PATH + "/test-ca-sha256.crt"),
    ("binary", "TEST_CA_CRT_RSA_SHA256_DER", DATA_FILES_PATH + "/test-ca-sha256.crt.der"),
    ("string", "TEST_CA_CRT_RSA_SHA1_PEM", DATA_FILES_PATH + "/test-ca-sha1.crt"),
    ("binary", "TEST_CA_CRT_RSA_SHA1_DER", DATA_FILES_PATH + "/test-ca-sha1.crt.der"),
    ("string", "TEST_CA_KEY_RSA_PEM", DATA_FILES_PATH + "/test-ca.key"),
    ("password", "TEST_CA_PWD_RSA_PEM", "PolarSSLTest"),
    ("binary", "TEST_CA_KEY_RSA_DER", DATA_FILES_PATH + "/test-ca.key.der"),
    ("string", "TEST_SRV_CRT_EC_PEM", DATA_FILES_PATH + "/server5.crt"),
    ("binary", "TEST_SRV_CRT_EC_DER", DATA_FILES_PATH + "/server5.crt.der"),
    ("string", "TEST_SRV_KEY_EC_PEM", DATA_FILES_PATH + "/server5.key"),
    ("binary", "TEST_SRV_KEY_EC_DER", DATA_FILES_PATH + "/server5.key.der"),
    ("string", "TEST_SRV_CRT_RSA_SHA256_PEM", DATA_FILES_PATH + "/server2-sha256.crt"),
    ("binary", "TEST_SRV_CRT_RSA_SHA256_DER", DATA_FILES_PATH + "/server2-sha256.crt.der"),
    ("string", "TEST_SRV_CRT_RSA_SHA1_PEM", DATA_FILES_PATH + "/server2.crt"),
    ("binary", "TEST_SRV_CRT_RSA_SHA1_DER", DATA_FILES_PATH + "/server2.crt.der"),
    ("string", "TEST_SRV_KEY_RSA_PEM", DATA_FILES_PATH + "/server2.key"),
    ("binary", "TEST_SRV_KEY_RSA_DER", DATA_FILES_PATH + "/server2.key.der"),
    ("string", "TEST_CLI_CRT_EC_PEM", DATA_FILES_PATH + "/cli2.crt"),
    ("binary", "TEST_CLI_CRT_EC_DER", DATA_FILES_PATH + "/cli2.crt.der"),
    ("string", "TEST_CLI_KEY_EC_PEM", DATA_FILES_PATH + "/cli2.key"),
    ("binary", "TEST_CLI_KEY_EC_DER", DATA_FILES_PATH + "/cli2.key.der"),
    ("string", "TEST_CLI_CRT_RSA_PEM", DATA_FILES_PATH + "/cli-rsa-sha256.crt"),
    ("binary", "TEST_CLI_CRT_RSA_DER", DATA_FILES_PATH + "/cli-rsa-sha256.crt.der"),
    ("string", "TEST_CLI_KEY_RSA_PEM", DATA_FILES_PATH + "/cli-rsa.key"),
    ("binary", "TEST_CLI_KEY_RSA_DER", DATA_FILES_PATH + "/cli-rsa.key.der"),
]


def read_as_c_array(filename: str) -> Iterator[str]:
    with open(filename, 'rb') as f:
        data = f.read(12)
        while data:
            yield ', '.join(['{:#04x}'.format(b) for b in data])
            data = f.read(12)

BINARY_START_TEMPLATE = '''
/* This is generated from {value}. */
/* BEGIN FILE binary macro {name} {value} */
#define {name} {{ \\
'''
'''
'''
BINARY_END_TEMPLATE = '''
}}
/* END FILE */
'''

def format_binary(name: str, filename: str) -> str:
    """Format the definition of a macro containing a byte array loaded from a file."""
    return (BINARY_START_TEMPLATE.format(name=name, value=filename) +
            '        '
            ', \\\n        '.join(read_as_c_array(filename)) +
            '\\' +
            BINARY_END_TEMPLATE.format(name=name, value=filename))

def read_lines(filename: str) -> Iterator[str]:
    with open(filename) as f:
        try:
            for line in f:
                yield line.strip()
        except:
            print(filename)
            raise

STRING_START_TEMPLATE = '''
/* This is taken from {value}. */
/* BEGIN FILE string macro {name} {value} */
#define {name} \\
'''
STRING_END_TEMPLATE = '''
/* END FILE */
'''

def format_string(name: str, filename: str) -> str:
    """Format the definition of a macro containing a string literal loaded from a file."""
    return (STRING_START_TEMPLATE.format(name=name, value=filename) +
            '    "' +
            '\\r\\n" \\\n    "'.join(read_lines(filename)) +
            '\\r\\n"' +
            STRING_END_TEMPLATE.format(name=name, value=filename))

PASSWORD_TEMPLATE = '''
#define {name} "{value}"
'''

def format_password(name: str, content: str) -> str:
    """Format the definition of a macro containing a simple string."""
    return PASSWORD_TEMPLATE.format(name=name, value=content)

HEADER = '''\
/*
 *  X.509 test certificates
 *
 *  Copyright The Mbed TLS Contributors
 *  SPDX-License-Identifier: Apache-2.0 OR GPL-2.0-or-later
 */

/* THIS FILE is generated by `framework/scripts/generate_test_cert_macros.py` */
/* *INDENT-OFF* */
'''

FOOTER = '''
/* End of generated file */
'''

def generate(values: List[Tuple[str, str, str]], output: str) -> None:
    """Generate C header file.
    """
    with open(output, 'w') as f:
        f.write(HEADER)
        for (type_, name, parameter) in values:
            if type_ == 'binary':
                chunk = format_binary(name, parameter)
            elif type_ == 'string':
                chunk = format_string(name, parameter)
            elif type_ == 'password':
                chunk = format_password(name, parameter)
            else:
                raise Exception('Unknown type: ' + type_)
            f.write(chunk)
        f.write(FOOTER)

def main() -> None:
    parser = argparse.ArgumentParser()
    default_output_path = os.path.join(TESTS_DIR, 'include', 'test', 'test_certs.h')
    parser.add_argument('--output', type=str, default=default_output_path)
    parser.add_argument('--list-dependencies', action='store_true')
    args = parser.parse_args()

    if args.list_dependencies:
        files_list = [arg[2] for arg in INPUT_ARGS]
        print(" ".join(files_list))
        return

    generate(INPUT_ARGS, args.output)

if __name__ == '__main__':
    main()
